apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: store-cluster-service-service
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: store-cluster-service-service
  chart:
    git: git@github.com:debjyoti-das/flux-helm-dsc
    path: charts/service
    ref: master
  values:
    app:
      name: store-cluster-service
      group: store-cluster-service
      namespace: dev
      replicaCount: 1
      container:
        image: prasantabarik/store-cluster-service:12
        port: 8093
      service:
        type: ClusterIP
        port: 8093
      version: v1
